import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';

export const roboto = Roboto({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en">
    <body className={roboto.className}>{children}</body>
  </html>
);

export default RootLayout;
